//! Regenerates `src/webauthn.rs` from the Windows SDK metadata shipped with `windows-bindgen`.

fn main() {
    let out = concat!(env!("CARGO_MANIFEST_DIR"), "/../../src/webauthn.rs");
    windows_bindgen::bindgen([
        "--out",
        out,
        "--sys",
        "--flat",
        "--extern",
        "--filter",
        "WebAuthNAuthenticatorGetAssertion",
        "WebAuthNAuthenticatorMakeCredential",
        "WebAuthNCancelCurrentOperation",
        "WebAuthNDeletePlatformCredential",
        "WebAuthNFreeAssertion",
        "WebAuthNFreeAuthenticatorList",
        "WebAuthNFreeCredentialAttestation",
        "WebAuthNFreePlatformCredentialList",
        "WebAuthNGetApiVersionNumber",
        "WebAuthNGetAuthenticatorList",
        "WebAuthNGetCancellationId",
        "WebAuthNGetErrorName",
        "WebAuthNGetPlatformCredentialList",
        "WebAuthNIsUserVerifyingPlatformAuthenticatorAvailable",
        "WEBAUTHN_API_VERSION_9",
        "WEBAUTHN_ASSERTION_VERSION_6",
        "WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_NONE",
        "WEBAUTHN_AUTHENTICATOR_ATTACHMENT_PLATFORM",
        "WEBAUTHN_AUTHENTICATOR_DETAILS_OPTIONS_CURRENT_VERSION",
        "WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_CURRENT_VERSION",
        "WEBAUTHN_AUTHENTICATOR_HMAC_SECRET_VALUES_FLAG",
        "WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_CURRENT_VERSION",
        "WEBAUTHN_CREDENTIAL_ATTESTATION_CURRENT_VERSION",
        "WEBAUTHN_CREDENTIAL_TYPE_PUBLIC_KEY",
        "WEBAUTHN_CTAP_ONE_HMAC_SECRET_LENGTH",
        "WEBAUTHN_CTAP_TRANSPORT_INTERNAL",
        "WEBAUTHN_HASH_ALGORITHM_SHA_256",
        "WEBAUTHN_USER_VERIFICATION_REQUIREMENT_REQUIRED",
    ]);
}
