name: CI

on: [ workflow_dispatch, push, pull_request ]

jobs:
  ci_stable:
    runs-on: windows-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Format check
        run: cargo fmt --check

      - name: Clippy check
        run: cargo clippy --no-deps --all-targets -- -D warnings

      - name: Build and Test
        run: cargo test --verbose -- --test-threads 1

      - name: Build and Test without default features
        run: cargo test --no-default-features --verbose -- --test-threads 1
        
      - name: Build examples
        run: cargo build --examples --verbose

  ci_msrv:
    runs-on: windows-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.88
          components: clippy

      - name: Clippy check
        run: cargo clippy --no-deps --all-targets -- -D warnings
